<script setup>
import { computed, onMounted, ref } from 'vue';
import { api } from './api.js';
import AiSchedulePreview from './components/AiSchedulePreview.vue';

const view = ref('teacher'); const loading = ref(false); const error = ref(''); const notice = ref('');
const teacher = ref({ lessons: [], students: [], orders: [], suggestion: null, draft: '' });
const parent = ref({ data: null, order: null }); const selectedLesson = ref(null);
const packages = [{ packageName: 'Demo 10 Lesson Package', creditQuantity: 10, amountCents: 50000 }, { packageName: 'Demo 20 Lesson Package', creditQuantity: 20, amountCents: 92000 }];
const available = (s) => s.totalCredits - s.attendedCredits - s.reservedCredits;
const formatDate = (v) => new Intl.DateTimeFormat('en-US', { weekday: 'short', month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' }).format(new Date(v));
const money = (c) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(c / 100);
const participants = (lesson) => lesson.participants?.map(({ student }) => student.name).join(' & ') ?? 'Student lesson';
const weekDates = computed(() => Array.from({ length: 5 }, (_, i) => new Date(new Date('2031-01-06T00:00:00').getTime() + i * 86400000)));
const hours = [15, 16, 17, 18, 19, 20]; const scheduled = computed(() => teacher.value.lessons.filter((lesson) => lesson.status === 'scheduled'));
const child = computed(() => parent.value.data?.students?.[0]);
async function loadTeacher() { const [lessons, students, orders] = await Promise.all([api.teacher.schedule(), api.teacher.students(), api.teacher.orders()]); teacher.value = { ...teacher.value, lessons, students, orders }; }
async function loadParent() { parent.value = { ...parent.value, data: await api.parent.dashboard() }; }
async function load() { loading.value = true; error.value = ''; try { view.value === 'teacher' ? await loadTeacher() : await loadParent(); } catch (e) { error.value = `Unable to load this demonstration (${e.message}). Start the API and retry.`; } finally { loading.value = false; } }
async function parse() { if (!teacher.value.draft.trim()) return; loading.value = true; error.value = ''; try { teacher.value.suggestion = (await api.teacher.parseSchedule(teacher.value.draft)).suggestion; } catch (e) { error.value = e.message === 'INVALID_AI_OUTPUT' ? 'The AI draft needs correction. Reword your request and retry.' : `AI preview is unavailable (${e.message}). Your note remains ready to retry.`; } finally { loading.value = false; } }
async function confirm(suggestion) { loading.value = true; error.value = ''; try { const studentIds = teacher.value.students.filter((s) => suggestion.studentNames.includes(s.name)).map((s) => s.id); await api.teacher.createLesson({ studentIds, startAt: suggestion.startAt }); teacher.value.suggestion = null; teacher.value.draft = ''; notice.value = 'Reservation confirmed and added to the weekly schedule.'; await loadTeacher(); } catch (e) { error.value = `Reservation not saved (${e.message}). Review availability and retry.`; } finally { loading.value = false; } }
async function transition(action) { if (!selectedLesson.value) return; loading.value = true; try { await api.teacher.updateLesson(selectedLesson.value.id, action); selectedLesson.value = null; notice.value = `Lesson ${action}d.`; await loadTeacher(); } catch (e) { error.value = `Lesson could not be ${action}d (${e.message}).`; } finally { loading.value = false; } }
async function purchase(option) { if (!child.value) return; loading.value = true; try { parent.value.order = await api.parent.createOrder({ studentId: child.value.id, ...option }); } catch (e) { error.value = `Could not create the demo order (${e.message}).`; } finally { loading.value = false; } }
async function simulatePayment() { loading.value = true; try { parent.value.order = await api.parent.simulatePayment(parent.value.order.id); notice.value = 'Simulated payment complete; the demonstration balance has refreshed.'; await loadParent(); } catch (e) { error.value = `Simulated payment could not complete (${e.message}).`; } finally { loading.value = false; } }
function select(next) { view.value = next; notice.value = ''; error.value = ''; load(); }
onMounted(load);
</script>

<template>
  <main class="app-shell">
    <header class="topbar"><a class="wordmark" href="#" @click.prevent="select('teacher')">Lessonline<span>AI</span></a><nav aria-label="Workspace"><button :class="{ active: view === 'teacher' }" @click="select('teacher')">Teacher workbench</button><button :class="{ active: view === 'parent' }" @click="select('parent')">Parent dashboard</button></nav><span class="demo-label">Synthetic demonstration</span></header>
    <p v-if="error" class="status error" role="alert">{{ error }}</p><p v-if="notice" class="status notice" role="status">{{ notice }}</p>
    <section v-if="view === 'teacher'" class="teacher-workbench"><div class="workbench-heading"><div><h1>Weekly teaching rhythm</h1><p>Review every AI draft before it changes a student schedule or lesson balance.</p></div><button class="button quiet" :disabled="loading" @click="loadTeacher">Refresh board</button></div>
      <div class="teacher-grid"><section class="schedule-board" aria-label="Weekly lesson schedule"><div class="schedule-head"><span>Time</span><span v-for="date in weekDates" :key="date.toISOString()">{{ new Intl.DateTimeFormat('en-US', { weekday: 'short', day: 'numeric' }).format(date) }}</span></div><div v-for="hour in hours" :key="hour" class="time-row"><time>{{ `${hour}:00` }}</time><div v-for="date in weekDates" :key="`${hour}-${date}`" class="schedule-cell"><button v-for="lesson in scheduled.filter((item) => new Date(item.startsAt).getUTCDay() === date.getDay() && new Date(item.startsAt).getUTCHours() === hour)" :key="lesson.id" class="lesson-chip" @click="selectedLesson = lesson"><strong>{{ participants(lesson) }}</strong><span>{{ new Date(lesson.startsAt).toISOString().slice(11, 16) }}</span></button><div v-if="teacher.suggestion && new Date(teacher.suggestion.startAt).getUTCDay() === date.getDay() && new Date(teacher.suggestion.startAt).getUTCHours() === hour" class="draft-chip"><strong>{{ teacher.suggestion.courseName }}</strong><span>AI preview</span></div></div></div></section>
        <div class="teacher-side"><section class="prompt-panel"><h2>Make a schedule draft</h2><label for="schedule-note">Describe the lesson</label><textarea id="schedule-note" v-model="teacher.draft" placeholder="e.g. Grade 8 Avery and Rowan, Wednesday at 18:30 for English" :disabled="loading"></textarea><button class="button primary" :disabled="loading || !teacher.draft.trim()" @click="parse">{{ loading ? 'Working…' : 'Create AI preview' }}</button></section><AiSchedulePreview :suggestion="teacher.suggestion" :students="teacher.students" :loading="loading" @confirm="confirm" @dismiss="teacher.suggestion = null" /></div></div>
      <section class="ledger"><div class="section-heading"><div><h2>Student lesson ledger</h2><p>Available = purchased − attended − scheduled.</p></div><span>{{ teacher.students.length }} synthetic students</span></div><div class="ledger-table" role="table"><div class="ledger-row ledger-label" role="row"><span>Student</span><span>Grade</span><span>Available</span><span>Scheduled</span><span>Attended</span></div><div v-for="s in teacher.students" :key="s.id" class="ledger-row" role="row"><strong>{{ s.name }}</strong><span>Grade {{ s.grade }}</span><span :class="{ danger: available(s) < 1 }">{{ available(s) }}</span><span>{{ s.reservedCredits }}</span><span>{{ s.attendedCredits }}</span></div></div></section>
    </section>
    <section v-else class="parent-dashboard"><div class="workbench-heading"><div><h1>Family lesson desk</h1><p>Only children belonging to this demonstration parent account appear here.</p></div><button class="button quiet" :disabled="loading" @click="loadParent">Refresh</button></div><div v-if="child" class="parent-grid"><section class="child-summary"><p class="student-name">{{ child.name }}</p><h2>Grade {{ child.grade }} English</h2><div class="credit-balance"><strong>{{ available(child) }}</strong><span>lessons available</span></div><dl><div><dt>Purchased</dt><dd>{{ child.totalCredits }}</dd></div><div><dt>Scheduled</dt><dd>{{ child.reservedCredits }}</dd></div><div><dt>Attended</dt><dd>{{ child.attendedCredits }}</dd></div></dl></section><section class="parent-lessons"><h2>This week & history</h2><ul v-if="child.lessons.length"><li v-for="lesson in child.lessons" :key="lesson.id"><strong>{{ formatDate(lesson.startsAt) }}</strong><span>{{ lesson.status }}</span></li></ul><p v-else class="empty-preview">No lesson records are available yet.</p></section><section class="purchase-panel"><h2>Add a lesson package</h2><p>For demonstration only — no real payment method is used.</p><div v-for="option in packages" :key="option.packageName" class="package-option"><div><strong>{{ option.packageName }}</strong><span>{{ option.creditQuantity }} lessons · {{ money(option.amountCents) }}</span></div><button class="button primary" :disabled="loading" @click="purchase(option)">Choose</button></div><div v-if="parent.order" class="payment-demo"><strong>{{ parent.order.status === 'paid' ? 'Simulated payment complete' : 'Demo order ready' }}</strong><p>{{ parent.order.packageName }} · {{ parent.order.paymentMode }} payment</p><button v-if="parent.order.status === 'pending'" class="button confirm" :disabled="loading" @click="simulatePayment">Complete simulated payment</button></div></section></div><p v-else class="empty-preview">Loading parent dashboard…</p></section>
    <div v-if="selectedLesson" class="lesson-drawer" role="dialog" aria-modal="true" aria-label="Lesson details"><button class="drawer-close" aria-label="Close lesson details" @click="selectedLesson = null">×</button><p class="preview-stamp">Scheduled lesson</p><h2>{{ participants(selectedLesson) }}</h2><p>{{ formatDate(selectedLesson.startsAt) }} · {{ selectedLesson.durationMinutes }} minutes</p><div class="preview-actions"><button class="button secondary" :disabled="loading" @click="transition('cancel')">Cancel reservation</button><button class="button confirm" :disabled="loading" @click="transition('complete')">Mark completed</button></div></div>
  </main>
</template>
